version: "3.9"
services:
  mongo:
    build:
      context: mongoDb
#      dockerfile: mongoDb/Dockerfile
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/postgresql/data/db/:/var/lib/postgresql/data
    ports:
      - "54325:5432"

volumes:
  mongo_data: { }
